/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package getuserinfo;

import job.user.summoner.App;
import org.junit.Test;

public class AppTest {
    @Test public void appHasAGreeting() {
        App classUnderTest = new App();

    }
}
