/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package job.user.puuid;

import org.junit.Test;

public class AppTest {
    @Test 
    public void appHasAGreeting() {
    }
}
